# Generated by Django 2.0.4 on 2018-05-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfav',
            name='article',
            field=models.IntegerField(default=0, verbose_name='文章编号'),
        ),
    ]
