# Generated by Django 2.0.4 on 2018-05-12 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='craete_time',
            new_name='create_time',
        ),
    ]
