# Generated by Django 2.0.4 on 2018-05-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20180512_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fav_num',
            field=models.IntegerField(default=0, verbose_name='收藏数'),
        ),
        migrations.AddField(
            model_name='post',
            name='praise_num',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
    ]
