# Generated by Django 2.0.4 on 2018-05-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20180512_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Img',
            field=models.ImageField(default='font/default.png', upload_to='font/%Y/%m', verbose_name='文章图片'),
        ),
    ]
